# foundry.toml
[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
solc = '0.8.19'

remappings = [
    '@chainlink/contracts-ccip=lib/ccip/contracts/',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@chainlink/local/=lib/chainlink-local/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
